import Header from '@/components/Header/Header';
import type { Metadata } from 'next'
import '../assets/scss/main.scss';

export const metadata: Metadata = {
  title: 'See Vie',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body >
        <Header />
        {children}
      </body>
    </html>
  )
}
